[2025-09-12T07:15:51.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T07:15:51.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-12T06:00:00+00:00 [queued]>
[2025-09-12T07:15:51.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-12T06:00:00+00:00 [queued]>
[2025-09-12T07:15:51.247+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-12T07:15:51.270+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_system> on 2025-09-12 06:00:00+00:00
[2025-09-12T07:15:51.292+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_hourly_predictions', 'check_system', 'scheduled__2025-09-12T06:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/tmp/tmpuhkxh0k0']
[2025-09-12T07:15:51.309+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-12T07:15:51.310+0000] {standard_task_runner.py:64} INFO - Started process 231 to run task
[2025-09-12T07:15:51.310+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask check_system
[2025-09-12T07:15:51.580+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-12T06:00:00+00:00 [running]> on host 2058836b81fe
[2025-09-12T07:15:53.334+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ops-team' AIRFLOW_CTX_DAG_ID='simple_hourly_predictions' AIRFLOW_CTX_TASK_ID='check_system' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-12T06:00:00+00:00'
[2025-09-12T07:15:53.337+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T07:15:53.455+0000] {logging_mixin.py:188} INFO - üîç Quick system check...
[2025-09-12T07:15:53.458+0000] {logging_mixin.py:188} INFO - ‚úÖ Disk space OK: 924.6GB
[2025-09-12T07:15:53.497+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è API not reachable
[2025-09-12T07:15:53.498+0000] {python.py:237} INFO - Done. Returned value was: system_checked
[2025-09-12T07:15:53.499+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T07:15:53.851+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_hourly_predictions, task_id=check_system, run_id=scheduled__2025-09-12T06:00:00+00:00, execution_date=20250912T060000, start_date=20250912T071551, end_date=20250912T071553
[2025-09-12T07:15:54.105+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-12T07:15:54.310+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-12T07:15:54.520+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
