[2025-09-11T08:00:01.355+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-11T08:00:01.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_daily_monitoring.check_predictions scheduled__2025-09-10T08:00:00+00:00 [queued]>
[2025-09-11T08:00:01.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_daily_monitoring.check_predictions scheduled__2025-09-10T08:00:00+00:00 [queued]>
[2025-09-11T08:00:01.423+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-11T08:00:01.457+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_predictions> on 2025-09-10 08:00:00+00:00
[2025-09-11T08:00:01.474+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_daily_monitoring', 'check_predictions', 'scheduled__2025-09-10T08:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/monitor_dag.py', '--cfg-path', '/tmp/tmp6cmhkq4h']
[2025-09-11T08:00:01.479+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1101) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-11T08:00:01.480+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask check_predictions
[2025-09-11T08:00:01.484+0000] {standard_task_runner.py:64} INFO - Started process 1111 to run task
[2025-09-11T08:00:01.592+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_daily_monitoring.check_predictions scheduled__2025-09-10T08:00:00+00:00 [running]> on host 02ae08abed04
[2025-09-11T08:00:01.974+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ops-team' AIRFLOW_CTX_DAG_ID='simple_daily_monitoring' AIRFLOW_CTX_TASK_ID='check_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T08:00:00+00:00'
[2025-09-11T08:00:01.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-11T08:00:01.995+0000] {logging_mixin.py:188} INFO - üìà Checking recent predictions...
[2025-09-11T08:00:01.996+0000] {logging_mixin.py:188} INFO - ‚ùå No predictions file found
[2025-09-11T08:00:01.996+0000] {python.py:237} INFO - Done. Returned value was: no_predictions
[2025-09-11T08:00:01.997+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-11T08:00:02.029+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_daily_monitoring, task_id=check_predictions, run_id=scheduled__2025-09-10T08:00:00+00:00, execution_date=20250910T080000, start_date=20250911T080001, end_date=20250911T080002
[2025-09-11T08:00:02.064+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-11T08:00:02.089+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-11T08:00:02.092+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
