[2025-09-11T09:00:03.252+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-11T09:00:03.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-11T08:00:00+00:00 [queued]>
[2025-09-11T09:00:03.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-11T08:00:00+00:00 [queued]>
[2025-09-11T09:00:03.361+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-11T09:00:03.385+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_system> on 2025-09-11 08:00:00+00:00
[2025-09-11T09:00:03.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2450) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-11T09:00:03.402+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_hourly_predictions', 'check_system', 'scheduled__2025-09-11T08:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/tmp/tmpbyq_nlj0']
[2025-09-11T09:00:03.409+0000] {standard_task_runner.py:64} INFO - Started process 2452 to run task
[2025-09-11T09:00:03.409+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask check_system
[2025-09-11T09:00:03.555+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-11T08:00:00+00:00 [running]> on host 02ae08abed04
[2025-09-11T09:00:04.087+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ops-team' AIRFLOW_CTX_DAG_ID='simple_hourly_predictions' AIRFLOW_CTX_TASK_ID='check_system' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-11T08:00:00+00:00'
[2025-09-11T09:00:04.092+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-11T09:00:04.130+0000] {logging_mixin.py:188} INFO - üîç Quick system check...
[2025-09-11T09:00:04.131+0000] {logging_mixin.py:188} INFO - ‚úÖ Disk space OK: 931.1GB
[2025-09-11T09:00:04.141+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è API not reachable
[2025-09-11T09:00:04.142+0000] {python.py:237} INFO - Done. Returned value was: system_checked
[2025-09-11T09:00:04.143+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-11T09:00:04.182+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_hourly_predictions, task_id=check_system, run_id=scheduled__2025-09-11T08:00:00+00:00, execution_date=20250911T080000, start_date=20250911T090003, end_date=20250911T090004
[2025-09-11T09:00:04.232+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-11T09:00:04.273+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-11T09:00:04.276+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
