[2025-09-12T09:00:02.800+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T09:00:02.871+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-12T08:00:00+00:00 [queued]>
[2025-09-12T09:00:02.885+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-12T08:00:00+00:00 [queued]>
[2025-09-12T09:00:02.886+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-12T09:00:02.909+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_system> on 2025-09-12 08:00:00+00:00
[2025-09-12T09:00:02.924+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4494) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-12T09:00:02.921+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_hourly_predictions', 'check_system', 'scheduled__2025-09-12T08:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/tmp/tmpf8o544ko']
[2025-09-12T09:00:02.925+0000] {standard_task_runner.py:64} INFO - Started process 4496 to run task
[2025-09-12T09:00:02.926+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask check_system
[2025-09-12T09:00:03.014+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-12T08:00:00+00:00 [running]> on host 2058836b81fe
[2025-09-12T09:00:03.126+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ops-team' AIRFLOW_CTX_DAG_ID='simple_hourly_predictions' AIRFLOW_CTX_TASK_ID='check_system' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-12T08:00:00+00:00'
[2025-09-12T09:00:03.128+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T09:00:03.156+0000] {logging_mixin.py:188} INFO - üîç Quick system check...
[2025-09-12T09:00:03.158+0000] {logging_mixin.py:188} INFO - ‚úÖ Disk space OK: 924.5GB
[2025-09-12T09:00:03.172+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è API not reachable
[2025-09-12T09:00:03.172+0000] {python.py:237} INFO - Done. Returned value was: system_checked
[2025-09-12T09:00:03.173+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T09:00:03.478+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_hourly_predictions, task_id=check_system, run_id=scheduled__2025-09-12T08:00:00+00:00, execution_date=20250912T080000, start_date=20250912T090002, end_date=20250912T090003
[2025-09-12T09:00:03.505+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-12T09:00:03.527+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-12T09:00:03.531+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
