[2025-09-11T10:27:58.628+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-11T10:27:58.717+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system manual__2025-09-11T10:27:56.236225+00:00 [queued]>
[2025-09-11T10:27:58.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system manual__2025-09-11T10:27:56.236225+00:00 [queued]>
[2025-09-11T10:27:58.735+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-11T10:27:58.759+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_system> on 2025-09-11 10:27:56.236225+00:00
[2025-09-11T10:27:58.770+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_hourly_predictions', 'check_system', 'manual__2025-09-11T10:27:56.236225+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/tmp/tmpdsd59t8e']
[2025-09-11T10:27:58.773+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3009) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-11T10:27:58.774+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask check_system
[2025-09-11T10:27:58.776+0000] {standard_task_runner.py:64} INFO - Started process 3019 to run task
[2025-09-11T10:27:58.870+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_hourly_predictions.check_system manual__2025-09-11T10:27:56.236225+00:00 [running]> on host 94617eeb311b
[2025-09-11T10:27:59.000+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ops-team' AIRFLOW_CTX_DAG_ID='simple_hourly_predictions' AIRFLOW_CTX_TASK_ID='check_system' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T10:27:56.236225+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-11T10:27:56.236225+00:00'
[2025-09-11T10:27:59.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-11T10:27:59.030+0000] {logging_mixin.py:188} INFO - üîç Quick system check...
[2025-09-11T10:27:59.031+0000] {logging_mixin.py:188} INFO - ‚úÖ Disk space OK: 927.7GB
[2025-09-11T10:27:59.042+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è API not reachable
[2025-09-11T10:27:59.043+0000] {python.py:237} INFO - Done. Returned value was: system_checked
[2025-09-11T10:27:59.043+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-11T10:27:59.298+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_hourly_predictions, task_id=check_system, run_id=manual__2025-09-11T10:27:56.236225+00:00, execution_date=20250911T102756, start_date=20250911T102758, end_date=20250911T102759
[2025-09-11T10:27:59.354+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-11T10:27:59.382+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-11T10:27:59.386+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
