[2025-09-12T05:38:35.599+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T05:38:35.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-11T16:00:00+00:00 [queued]>
[2025-09-12T05:38:35.846+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-11T16:00:00+00:00 [queued]>
[2025-09-12T05:38:35.849+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-12T05:38:35.952+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_system> on 2025-09-11 16:00:00+00:00
[2025-09-12T05:38:36.075+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_hourly_predictions', 'check_system', 'scheduled__2025-09-11T16:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/tmp/tmpcgoagt95']
[2025-09-12T05:38:36.091+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1086) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-12T05:38:36.093+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask check_system
[2025-09-12T05:38:36.095+0000] {standard_task_runner.py:64} INFO - Started process 1104 to run task
[2025-09-12T05:38:36.678+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_hourly_predictions.check_system scheduled__2025-09-11T16:00:00+00:00 [running]> on host c556a26b394a
[2025-09-12T05:38:37.563+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ops-team' AIRFLOW_CTX_DAG_ID='simple_hourly_predictions' AIRFLOW_CTX_TASK_ID='check_system' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-11T16:00:00+00:00'
[2025-09-12T05:38:37.602+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T05:38:37.725+0000] {logging_mixin.py:188} INFO - üîç Quick system check...
[2025-09-12T05:38:37.729+0000] {logging_mixin.py:188} INFO - ‚úÖ Disk space OK: 926.0GB
[2025-09-12T05:38:37.759+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è API not reachable
[2025-09-12T05:38:37.767+0000] {python.py:237} INFO - Done. Returned value was: system_checked
[2025-09-12T05:38:37.769+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T05:38:39.225+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_hourly_predictions, task_id=check_system, run_id=scheduled__2025-09-11T16:00:00+00:00, execution_date=20250911T160000, start_date=20250912T053835, end_date=20250912T053839
[2025-09-12T05:38:39.513+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-12T05:38:39.610+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-12T05:38:39.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
